name: Generate README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Bash
      uses: shivammathur/setup-bash@v1

    - name: Run Makefile to generate README.md
      run: make
    
    - name: Commit and push README.md
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions[bot]
        author_email: github-actions[bot]@users.noreply.github.com
        message: "Generate README.md"
        add: "README.md"
