name: Generate README

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # This runs on the latest Ubuntu image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code

    - name: Show directory contents
      run: |
        pwd  # Print working directory
        ls -al  # List all files to check if Makefile is present

    - name: Run Makefile to generate README.md
      run: make  # Run the Makefile

    - name: Commit and push README.md
      uses: EndBug/add-and-commit@v7  # Commit the generated README.md back to the repo
      with:
        author_name: github-actions[bot]  # The commit will be made by GitHub Actions
        author_email: github-actions[bot]@users.noreply.github.com
        message: "Generate README.md"  # Commit message
        add: "README.md"  # Only add README.md to the commit
