name: Generate README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Make
      run: sudo apt-get install make
      
    - name: Run Make to generate README.md
      run: make

    # Debug step to check README.md content after 'make' runs
    - name: Debug Make Output
      run: cat README.md
      
    - name: Commit and push README.md
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add README.md
        git commit -m "Generated README"
        git push
